// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cacbmrhipwtbtmmxqebt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhY2JtcmhpcHd0YnRtbXhxZWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNzYwNDIsImV4cCI6MjA2NDY1MjA0Mn0.tbzSZ9jGtmg1_QEy_m8oejlKPMD5yCYq6R2C0qYkSys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);